# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170522_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='Group',
        ),
        migrations.DeleteModel(
            name='CciGroup',
        ),
    ]
