# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170522_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CciGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='Group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CciGroups'),
        ),
    ]
