# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170518_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='DOB',
            field=models.DateField(max_length=8),
        ),
    ]
