# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170518_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=20)),
                ('TeamLead', models.CharField(max_length=20)),
                ('ClientName', models.CharField(max_length=200)),
                ('Tech', models.CharField(max_length=200)),
            ],
        ),
    ]
