# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(max_length=10)),
                ('ProductName', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('UnitPrice', models.CharField(max_length=10)),
                ('QtyInStock', models.CharField(max_length=10)),
                ('IsDiscontinued', models.CharField(max_length=5)),
                ('ReOrderLevel', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=10)),
                ('Product', models.CharField(max_length=50)),
                ('QtySold', models.CharField(max_length=10)),
                ('Rate', models.CharField(max_length=10)),
            ],
        ),
    ]
