# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teammembers_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='asd',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
