# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_teams_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='Group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CciGroups'),
        ),
    ]
