# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_teams_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='Team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.Teams'),
        ),
    ]
