# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170523_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='asd',
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.Teams'),
        ),
    ]
